
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Darwin - 25.0.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library 'System' not found
      cc: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is AppleClang, found in:
        /Users/vyacheslav/SSE3_OpenGL/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library 'c++' not found
      c++: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is AppleClang, found in:
        /Users/vyacheslav/SSE3_OpenGL/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-vDUypJ"
      binary: "/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-vDUypJ"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/Users/vyacheslav/.brew/Cellar/libressl/4.0.0/lib"
      CMAKE_OSX_ARCHITECTURES: "arm64"
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-vDUypJ'
        
        Run Build Command(s): /Users/vyacheslav/.brew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_e7949/fast
        You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
        
      exitCode: 69
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/vyacheslav/.brew/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
    directories:
      source: "/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-R2xjiD"
      binary: "/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-R2xjiD"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-L/Users/vyacheslav/.brew/Cellar/libressl/4.0.0/lib"
      CMAKE_OSX_ARCHITECTURES: "arm64"
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/vyacheslav/SSE3_OpenGL/CMakeFiles/CMakeScratch/TryCompile-R2xjiD'
        
        Run Build Command(s): /Users/vyacheslav/.brew/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_27e13/fast
        You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
        
      exitCode: 69
...
